version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api: 
    container_name: api-container
    image: node:15
    working_dir: /usr/src/curso-pracc-3
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes: 
      - ./dist/:/usr/src/curso-pracc-3/dist/
      - ./package.json:/usr/src/curso-pracc-3/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links: 
      - mongo