version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    build: .
    restart: always
    image: 'curso-pracc-4'
    command: npm start
    volumes:
      - ./dist:/usr/src/curso-pracc-4/dist
    ports:
      - '5555:5555'
    links:
      - mongo
