version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    image: node:14
    working_dir: /usr/src/curso-pracc-4
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/curso-pracc-4/dist/
      - ./package.json:/usr/src/curso-pracc-4/package.json
    ports:
      - '5555:5555'
    links:
      - mongo
